<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '服务领域';
$typeArr[3] = '车型展示';
$typeArr[4] = '新闻资讯';
$typeArr[5] = '人才招聘';
$typeArr[6] = '联系我们';
$typeArr[7] = '公司简介';
$typeArr[8] = '企业文化';
$typeArr[9] = '企业理念';
$typeArr[10] = '全国反空货运';
$typeArr[11] = '市内专车运输';
$typeArr[12] = '大型货运车';
$typeArr[13] = '中型货运车';
$typeArr[14] = '小型货运车';
$typeArr[15] = '公司新闻';
$typeArr[16] = '行业新闻';
$typeArr[17] = '货运知识';
$typeArr[18] = '联系方式';
$typeArr[19] = '留言中心';
$typeArr[20] = '图文动态';
?>