<?php
$z[0]=Array("pubdate","\r\n      \$a=\"\".strftime('%Y/%m/%d',@me).\"\";\r\n      \$b=strftime('%Y/%m/%d',@me);\r\n      \$ntime = time();\r\n      \$day3 = 3600 * 24 * 3;\r\n      if((\$ntime - @me) < \$day3) @me = \$a;\r\n      else @me =\$b;\r\n    ",10,257);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",273,288);
$z[2]=Array("fulltitle","",297,348);
$z[2][4]['function']="htmlspecialchars(@me)";
$z[3]=Array("title","",350,364);

?>