<?php
$z[0]=Array("pubdate","\r\n      \$a=\"\".strftime('%m/%d',@me).\"\";\r\n      \$b=strftime('%m/%d',@me);\r\n      \$ntime = time();\r\n      \$day3 = 3600 * 24 * 3;\r\n      if((\$ntime - @me) < \$day3) @me = \$a;\r\n      else @me =\$b;\r\n    ",10,251);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",283,298);
$z[2]=Array("fulltitle","",307,325);
$z[3]=Array("title","",327,341);
$z[4]=Array("info","",351,364);

?>